# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

splotch_rcpp <- function(base, iterations = 3L) {
    .Call(`_paint_splotch_rcpp`, base, iterations)
}

